### ISSUE TITLE
Help in Lunching

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [Overmiind/Puppeteer-sharp-extra#44] opened 2022-11-28 00:14 UTC
System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task`1<PuppeteerSharp.Browser> PuppeteerSharp.Puppeteer.LaunchAsync(PuppeteerSharp.LaunchOptions, Microsoft.Extensions.Logging.ILoggerFactory)'.'

**Comment by KoalaBear84** [comment] 2022-11-28 07:28
More info will be helpful, looks like a exact duplicate of my ticket. #42

**Comment by namilkimfree** [comment] 2023-01-03 04:45
Fixed this Issue

**Comment by Overmiind** [comment] 2023-03-16 18:40
Fixed by [R3D4NG3L](https://github.com/Overmiind/Puppeteer-sharp-extra/pull/49)
Please update the NuGet package version of Puppeteer Extra Sharp to 2.0.

**Closed by Overmiind** 2023-03-16 18:40 UTC
